name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: >-
    ${{ github.ref != 'refs/heads/main' &&
        github.event_name != 'merge_group' &&
        !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install linter
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
      - name: Run linter
        run: python3 -m flake8 --show-source .

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install formatter
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install autopep8
      - name: Run formatting tool
        run: python3 -m autopep8 -a -i -r .
      - name: Compare formatted version with unformatted
        run: git diff --exit-code

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install isort
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install isort
      - name: isort version
        run: python3 -m isort --version
      - name: Run isort
        run: python3 -m isort .
      - name: Compare formatted version with unformatted
        run: git diff --exit-code
      - name: List files with error (open this section to see the list of files that failed this check)
        run: git diff | grep "diff --git"; exit 1
        if: failure()
